# Set the build language to Python
language: python

# Set the python version to 3.6
python: 3.6

install:
  - pip install codecov

script:
  - coverage run --omit="venv/*","docs/*",".github/*" -m pysky -sd 2020-08-01 -st 21:30 -ed 2020-08-02 -et 01:45 && codecov -t e9d50f9d-761c-4b65-83aa-faf40fcc3792
